function I = readInAnImage(msg)
[filename, pathname] = uigetfile(...    
    {'*.jpg; *.png; *.JPG; *.jpeg; *.JPEG; *.img; *.IMG; *.tif; *.TIF; *.tiff, *.TIFF','Supported Files (*.jpg,*.img,*.tiff,)'; ...
    '*.jpg','jpg Files (*.jpg)';...
    '*.png','png Files (*.png)';...
    '*.JPG','JPG Files (*.JPG)';...
    '*.jpeg','jpeg Files (*.jpeg)';...
    '*.JPEG','JPEG Files (*.JPEG)';...
    '*.img','img Files (*.img)';...
    '*.IMG','IMG Files (*.IMG)';...
    '*.tif','tif Files (*.tif)';...
    '*.TIF','TIF Files (*.TIF)';...
    '*.tiff','tiff Files (*.tiff)';...
    '*.TIFF','TIFF Files (*.TIFF)'},...
    msg);

% No image read in
if isequal(filename,0)
    error(' Load Error: No files selected! Load cancelled.')
end
    
% Show original image
fullname = fullfile(pathname,filename);
I = imread(fullname);
end

